id: ca5bcadb6a7b40d8abb414f369814846
initial_creation_type: ocr
source_metadata:
  volumes:
    1cf1050cd0cc408c87bf0d7f460ae7cd:
      base_file: v018.txt
      image_group_id: I1PD95863
      title: བྱང་ཆུབ་སེམས་ཀྱི་འགྲེལ་པ།
      total_pages: 1634
      volume_number: 18
